# -*- coding: utf-8 -*-
"""animacao_projetil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ERI9JXvgYBczfZNXUDKW918h55nJw0-s
"""

import matplotlib.animation
import matplotlib.pyplot as plt
import numpy as np
plt.rcParams["animation.html"] = "jshtml"
plt.rcParams['figure.dpi'] = 150  
plt.ioff()

fig = plt.figure()

def animate(k):
    plt.cla()
    t = 0.1*k
    plt.scatter(186.636804778*t, 50*t - 0.5*10*t**2) # lançamento em 15°
    plt.scatter(86.5950813994*t, 50*t - 0.5*10*t**2) # lançamento em 30°
    plt.scatter(50*t, 50*t - 0.5*10*t**2) # lançamento em 45°
    plt.scatter(28.8666936089*t, 50*t - 0.5*10*t**2) # lançamento em 60°
    plt.scatter(13.397283031*t, 50*t - 0.5*10*t**2) # lançamento em 75°
    plt.xlim(0,1500)
    plt.ylim(0,150)

anim = matplotlib.animation.FuncAnimation(fig, animate, frames=100, interval=10)

# to save the animation, uncomment the following three lines
f = r"Animacao.mp4" 
writervideo = matplotlib.animation.FFMpegWriter(fps=60) 
anim.save(f, writer=writervideo,dpi =150)

print("Aqui vamos fazer uma alteração")